<?php

namespace Mgn\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findAllWithForums()
    {
    	$qb = $this->createQueryBuilder('c');
		$qb->leftJoin('c.forums', 'f');
        $qb->addSelect('f');
		$qb->orderBy('c.sort', '');
		$qb->addOrderBy('f.sort', '');
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getResult();
    }
}
