<?php

namespace Mgn\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
	public function findAllMark($user)
    {
    	$qb = $this->createQueryBuilder('m');
		$qb->where('m.user = :user')
			->setParameter('user', $user);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getResult();
    }

    public function findMark($user, $forum)
    {
    	$qb = $this->createQueryBuilder('m');
		$qb->where('m.user = :user')
			->setParameter('user', $user)
	       ->andwhere('m.forum = :forum')
	         ->setParameter('forum', $forum);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getOneOrNullResult();
    }
}
