<?php

namespace Mgn\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
	public function findOneWithPosts($id, $page, $nb_posts_page)
    {
    	$qb = $this->createQueryBuilder('t');
		$qb->leftJoin('t.forum', 'f');
        $qb->addSelect('f');
		$qb->leftJoin('f.category', 'c');
        $qb->addSelect('c');
		$qb->leftJoin('t.messages', 'm');
		$qb->addSelect('m');
		$qb->leftJoin('m.author', 'u');
		$qb->addSelect('u');
		$qb->orderBy('m.date', '');
		$qb->where('t.id = :id')
			->setParameter('id', $id);
		$qb->setFirstResult(($page-1)*$nb_posts_page)->setMaxResults($nb_posts_page);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getOneorNullResult();
    }

    public function findOneByIdWithLastPost($topicId)
    {
    	$qb = $this->createQueryBuilder('t');
		$qb->leftJoin('t.lastMessage', 'l');
        $qb->addSelect('l');
		$qb->where('t.id = :id')
			->setParameter('id', $topicId);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getOneorNullResult();
    }
}
