<?php

namespace Mgn\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{
	public function findAllView($user)
    {
    	$qb = $this->createQueryBuilder('v');
		$qb->leftJoin('v.topic', 't');
		$qb->addSelect('t');
		$qb->where('v.user = :user')
			->setParameter('user', $user);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getResult();
    }

    public function findViewsForForum($user, $forum)
    {
    	$qb = $this->createQueryBuilder('v');
		$qb->where('v.user = :user')
			->setParameter('user', $user)
	       ->andwhere('v.forum = :forum')
	         ->setParameter('forum', $forum);
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getResult();
    }

    public function findViewsForTopic($user, $topic)
    {
    	$qb = $this->_em->createQueryBuilder();

	    $qb->select('v')
	       ->from('MgnForumBundle:View', 'v')
	       ->where('v.user = :user')
	         ->setParameter('user', $user)
	       ->andwhere('v.topic = :topic')
	         ->setParameter('topic', $topic);
	
	    return $qb->getQuery()
	               ->getOneOrNullResult();
    }
}
