<?php

namespace Mgn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
	public function loadGroupWithUsers($id)
    {
        $q = $this
            ->createQueryBuilder('g')
            ->leftJoin('g.users', 'to')
            ->leftJoin('to.user', 'u')
            ->select('g, to, u')
            ->where('g.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        try {
            // La méthode Query::getSingleResult() lance une exception
            // s'il n'y a pas d'entrée correspondante aux critères
            $group = $q->getSingleResult();
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('Unable to find an active admin AcmeUserBundle:User object identified by "%s".', $id), 0, $e);
        }

        return $group;
    }
}
