<?php

namespace Mgn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserToGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToGroupRepository extends EntityRepository
{
	public function loadGroupForUser($id)
    {
        $q = $this
            ->createQueryBuilder('ug')
            ->leftJoin('ug.group', 'g')
            ->select('ug, g')
            ->where('ug.user = :user')
            ->setParameter('user', $id)
            ->getQuery();

        try {
            // La méthode Query::getSingleResult() lance une exception
            // s'il n'y a pas d'entrée correspondante aux critères
            $groups = $q->getResult();
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('Unable to find an active admin AcmeUserBundle:User object identified by "%s".', $username), 0, $e);
        }

        return $groups;
    }
}
