<?php

namespace Mgn\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findCategoryDefault()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->where('c.slug = :slug')
			->setParameter('slug', 'non-classe');
	                // Enfin, on retourne le résultat.
	        return $qb->getQuery()
	                   ->getOneOrNullResult();
       
	}
}
