<?php

namespace Mgn\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentsRepository extends EntityRepository
{
}
