# src/Mgn/UserBundle/Resources/config/services.yml
services:
  login_listener:
    class: Mgn\UserBundle\Listener\LoginListener
    arguments: [@security.context, @doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }