parameters:
#    mgn_admin.example.class: Mgn\AdminBundle\Example

services:
#    mgn_admin.example:
#        class: %mgn_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
