<?php

namespace Mgn\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function findMessagesAfterDate($date)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.date > :date')
            ->setParameter('date', $date);
                    // Enfin, on retourne le résultat.
            return $qb->getQuery()
                       ->getResult();
    }
}
